export default {
  app: {
    modals: {
      platforms: {
        opened: false,
      },
      changePassword: {
        opened: false,
      },
      manageAccount: {
        opened: false,
      },
      exportPrivateKey: {
        opened: false,
      },
      forgotPassword: {
        opened: false,
      },
    },
  },
  coin: {
    list: [],
  },
  upcoming: {
    list: [],
  },
  monitor: {
    list: [],
    loading: false,
    monitorRefreshLoading: false,
    monitorAddLoading: false,
    monitorUpdating: false,
    monitorAddError: false,
    monitorAddOpened: false,
    monitorAddSelectedList: [],
    masternodeSearchText: '',
    masternodeSearchResult: [],
    masternodeSearchLoading: false,
    masternodeSearchResultNotFound: false,
    monitorRemoveItem: {},
    monitorRemoveError: false,
    monitorRemoveLoading: false,
    monitorRemoveOpened: false,
  },
  alert: {
    list: [],
    loading: false,
    alertAddLoading: false,
    alertAddError: false,
    alertAddOpened: false,
    alertAddSelectedList: [],
    masternodeSearchText: '',
    masternodeSearchResult: [],
    masternodeSearchLoading: false,
    alertRemoveError: false,
    alertRemoveLoading: false,
    alertRemoveOpened: false,
  },
  auth: {
    loading: true,
    login: {
      loginLoading: false,
      loginOpened: false,
      loginError: false,
      loginRejected: false,
      loginFulfilled: false,
      email: '',
      password: '',
    },
    external: {
      externalLoginLoading: false,
      externalLoginRejected: false,
    },
    signup: {
      signupLoading: false,
      signupOpened: false,
      signupError: false,
      signupRejected: false,
      signupFulfilled: false,
      email: '',
      password: '',
      passwordConfirmation: '',
      privateKeyCopied: false,
      privateKeyFulfilled: false,
      privateKeyError: false,
    },
    forgotPassword: {
      forgotPasswordLoading: false,
      forgotPasswordError: false,
      forgotPasswordRejected: false,
      forgotPasswordFulfilled: false,
    },
    renewPassword: {
      checkRenewPasswordLoading: false,
      checkRenewPasswordError: false,
      checkRenewPasswordRejected: false,
      checkRenewPasswordFulfilled: false,
      renewPasswordLoading: false,
      renewPasswordError: false,
      renewPasswordRejected: false,
      renewPasswordFulfilled: false,
    },
    user: {},
    isAuthenticated: false,
    token: '',
  },
};
